_format_version: "2.1"
services:
  - name: auth-service
    url: http://127.0.0.1:1231
    routes:
      - name: auth
        paths:
          - /auth
  - name: auth-service-2
    url: https://api.github.com
    routes:
      - name: auth2
        paths:
          - /h